### ISSUE TITLE
Log-on not successful. For no discernable reason

### ISSUE THREAD

**Issue by beomusxyz** [LukeSmithxyz/mutt-wizard#892] opened 2022-11-03 12:32 UTC
I am unable to get mutt-wizard to work, which frustrates me, because this used to work flawlessly..

I am unable to log into any of my mail accounts from mutt-wizard, however all of the same accounts with the same imap/smtp configs work like a charm in thunderbird on the same machine. I have no idea what is going on.

```
$ mw -a address@example.com -s mail.example2.com -i mail.example2.com 

$ Enter password for address@example.com:
$ Retype password for address@example.com:
$ Log-on not successful.
```

**Comment by Linus-J** [comment] 2022-11-16 23:12
Hi there,

I had a similar issue when logging into a Google mail account. If you by chance are using a Gmail account as well, there is a relevant solved issue was submitted on the neomutt GitHub repo [here](https://github.com/neomutt/neomutt/issues/3453).

If in fact you're with a different email host, then it could be worth checking if there are any similar issues posted over on the neomutt repo if you haven't done so already.

**Comment by pdillo** [comment] 2022-12-04 20:15
Same issue here

**Comment by larsinka** [comment] 2022-12-07 13:35
Same problem here! 
Ubuntu 22.04.1
mail@icloud.com

**Comment by tienbuigia** [comment] 2022-12-19 14:41
Same issue here.

**Comment by ducks4rule** [comment] 2022-12-21 17:43
Same issue here

**Comment by LukeSmithxyz** [comment] 2022-12-21 18:02
Couple possibilities here:

1. mutt-wizard now uses `curl` to check connections, so this is a dependency. It might not have been added to repos or old users might not have it installed.
2. Something in the `curl` command test is not generalizable to all mail servers.
3. In each of the reported cases, something different is going on and there is no single issue.

If there is something wrong, it's (2), but I've never used a mail server where `curl` doesn't work as it should here. If people with issues could report their servers, that would aid in troubleshooting.

Note that you can test curl manually with a command like this:

```
curl --location-trusted -s -m 5 --user "accountname:password" --url "imaps://imap.example.org:993"
```

**Comment by LukeSmithxyz** [comment] 2023-01-05 17:40
It's impossible for me to diagnose any issue without people telling me what servers they use. I have not been able to find a server that I have a mail account with that has this issue.

Note again that Google and iCloud have a vendor lock-out policies that disable third-party applications unless you specifically enable them or get an application-specific password. As always, mostly people run into this issue.

**Comment by kulych** [comment] 2023-01-09 21:09
Hello, same issue here. Protonmail + ProtonBridge.

This is the output of `curl .... -vvv`.

```
*   Trying 127.0.0.1:1143...
* Connected to 127.0.0.1 (127.0.0.1) port 1143 (#0)
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* [CONN-0-0][CF-SSL] TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* [CONN-0-0][CF-SSL] (204f) (IN), , Unknown (42):
{ [5 bytes data]
* OpenSSL/3.0.7: error:0A00010B:SSL routines::wrong version number
* Closing connection 0

Log-on not successful.
```


I can reproduce the same error for non-protonmail (for arbitrary credentials):
`mw -a some@email.com -i imap.forpsi.com -I 143 -s smtp.forpsi.com -S 587 -x "password"`

Hope it helps!

**Comment by LukeSmithxyz** [comment] 2023-01-09 21:34
Protonmail doesn't work with mw. I used to maintain compatibility with it, but it was too much of a hassle.

See ef5bac2b55e3bd665d103eff4ea435ecaa9db22c

**Comment by beomusxyz** [comment] 2023-01-11 02:48
> Hi there,
> 
> I had a similar issue when logging into a Google mail account. If you by chance are using a Gmail account as well, there is a relevant solved issue was submitted on the neomutt GitHub repo [here](https://github.com/neomutt/neomutt/issues/3453).
> 
> If in fact you're with a different email host, then it could be worth checking if there are any similar issues posted over on the neomutt repo if you haven't done so already.

My apologies for the absence, i am using my own personal mail server, and Vincent Canfield's cock.li servers. neither of them are working, which is what led me to think this is an issue with mutt-wizard, not the mailserver configurations.

**Comment by beomusxyz** [comment] 2023-01-11 02:51
> It's impossible for me to diagnose any issue without people telling me what servers they use. I have not been able to find a server that I have a mail account with that has this issue.
> 
> Note again that Google and iCloud have a vendor lock-out policies that disable third-party applications unless you specifically enable them or get an application-specific password. As always, mostly people run into this issue.

Hi luke, my apologies for the absence, please see my above comment.  If there's any more information you would like me to provide with regards to this issue, please let me know. You write some damn good configs.

**Comment by KebabLord** [comment] 2023-01-11 21:33
> > Hi there,
> > I had a similar issue when logging into a Google mail account. If you by chance are using a Gmail account as well, there is a relevant solved issue was submitted on the neomutt GitHub repo [here](https://github.com/neomutt/neomutt/issues/3453).
> > If in fact you're with a different email host, then it could be worth checking if there are any similar issues posted over on the neomutt repo if you haven't done so already.
> 
> My apologies for the absence, i am using my own personal mail server, and Vincent Canfield's cock.li servers. neither of them are working, which is what led me to think this is an issue with mutt-wizard, not the mailserver configurations.

I'm also using vincent's mail services and they're currently working fine. Cock.li's uptime is pretty bad so sometimes it's basically an error at server side. A weird problem i came accross when using muttwizard is pasting password is sometimes doesn't work so i advice you to enter your password one by one.

**Comment by LukeSmithxyz** [comment] 2023-01-12 15:35
Just tried a cockmail account of mine and it works fine.

Are people sure they have curl installed? This is a required dependency now that does the test login. I *assumed* that everyone would have it anyway, but I suppose there are some systems where it never gets pulled.

**Comment by Cienaxle** [comment] 2023-01-13 00:37
I've had the same problem. Trying to set up neomutt for the first time using mw. Connecting to my email server (POP/SMTP) gave the same "Log in not successful" error as the OP. Curl is installed on my system. Trying to use mpop and msmtp to fetch and send.

I was able to force the account to set up using the '-f' flag, with the plan that once it was set up I could narrow down the problem. Running mw -Y produced:
```
mpop: authentication failed (method PLAIN)
mpop: error during mail retrieval 
```
I went in to the mpop config and changed:
```
passwordeval pass <<my email>>
```
to:
```
password <<my password>>
```
and it worked. Same thing for msmtp. I'd rather not have passwords as clear text, though.

For some reason, 'pass <my email>' does not send the password to mpop or msmtp. I've set it up correctly. It returns the password when entered in a shell. I thought perhaps there might be a newline at the end of the encrypted password, but no. For now neomutt + mw will work with unencrypted passwords, but that's really far from ideal.

**Comment by beomusxyz** [comment] 2023-01-13 06:08
> > > Hi there,
> > > I had a similar issue when logging into a Google mail account. If you by chance are using a Gmail account as well, there is a relevant solved issue was submitted on the neomutt GitHub repo [here](https://github.com/neomutt/neomutt/issues/3453).
> > > If in fact you're with a different email host, then it could be worth checking if there are any similar issues posted over on the neomutt repo if you haven't done so already.
> > 
> > 
> > My apologies for the absence, i am using my own personal mail server, and Vincent Canfield's cock.li servers. neither of them are working, which is what led me to think this is an issue with mutt-wizard, not the mailserver configurations.
> 
> I'm also using vincent's mail services and they're currently working fine. Cock.li's uptime is pretty bad so sometimes it's basically an error at server side. A weird problem i came accross when using muttwizard is pasting password is sometimes doesn't work so can you try to enter your password one by one?
> 
> Certificates are another problem on old stable systems I came across, I had to install certficate authorities manually in order to get ssl work.

it may well be the password thing, but i did investigate that. typing it by hand, escaping special characters for the shell, and even trying a password that had no special characters. i can comfortably say it's probably not cock.li's uptime, as i had the same issues on my own mailserver. curious...

**Comment by Shane-XB-Qian** [comment] 2023-01-13 08:20
i am interesting how you input the passwd, type the char one by one, or yank from somewhere then try to ctrl+shift+v something like that to paste it?

**Comment by Cienaxle** [comment] 2023-01-13 15:45
@beomusxyz , does your password contain special characters?

I was able to resolve my problem as described above (perhaps the same as yours) by changing to a password without special characters.

The problem is with msmtp. It seems to fail when special characters (probably one specific character) are in the password, but only when piped in through 'pass' via the 'passwordeval' config option. Mpop has the same problem.

On my system: msmtp version 1.8.6, mpop version 1.4.6

**Comment by beomusxyz** [comment] 2023-01-18 01:47
> @beomusxyz , since you've mentioned that you've tried a password without special characters, my problem as described above may be different than yours. I was able to resolve my problem by changing to a password without special characters. Alphanumerics only ([a-z][A-Z][0-9]).
> 
> The problem is with msmtp. It seems to fail when special characters (probably one specific character) are in the password, but only when piped in from 'pass' via the 'passwordeval' config option. Mpop has the same problem.
> 
> On my system: msmtp version 1.8.6, mpop version 1.4.6

i will try this again, with only alphanumerics. i think i tried to use periods or dashes in the previous password.




> i am interesting how you input the passwd, type the char one by one, or yank from somewhere then try to ctrl+shift+v something like that to paste it?

i was originally pasting it, but i did type it in char by char after that, yes.

**Comment by AristoclesNine** [comment] 2023-01-22 07:51
I've have the same problem today, and I solved the problem by running mw with -f and -x.

**Comment by Cienaxle** [comment] 2023-01-25 17:54
I can confirm the same results as @AristoclesNine. If the problem is with alphanumerics in the password, it may be resolved by entering the password non-interactively with -x option. Put the password in single quotes, however.

Using muttwizard v3.3.1 (latest released on 30/4/2022), pass v1.74, mpop v1.4.16, and msmtp v1.8.16 (all from Ubuntu Mate 22.04 stable). I have found that running 'mw -a' using the -x option with an unquoted password resulted in unpredictable errors when the password contains certain special characters.

Shell history shows that the entry was split at a '!!' in the password and the command preceding it in shell history was re-inserted at that point. Then mw would attempt to parse that command, resulting in an error. For example:
```
man mw
mw -a foo@bar.com -P -x qwerty!!uiop -i imap.bar.com
```
becomes:
```
mw -a foo@bar.com -P -x qwertyman mwuiop -i imap.bar.com
```
I am not sure if this is a problem with muttwizard or with my shell, and I apologize for introducing what may be an issue which may be unrelated to the original post. I can log a new issue if @LukeSmithxyz thinks it is worth investigating.

**Comment by LukeSmithxyz** [comment] 2023-01-26 14:01
For more trouble-shooting, if someone has an error inputting a password and mw fails to install it, just run `pass your@mailaddress.com` and that should show the password it stored.

Check if that is the same as the password you inputted.

**Comment by leekool** [comment] 2023-01-27 12:08
I just ran the exact same command as I did back on Nov 19, 2022 when I was having issues and it worked fine

`mw -a lee@imre.al -u lee -i mail.imre.al -s mail.imre.al -S 587 -x ***********`

 I've ran pacman -Syu since then so I can only assume something was updated between then and now that fixed the issue.

**Closed** 2023-04-24 14:45 UTC

**Comment by callhands** [comment] 2026-04-28 03:30
I had this same issue. The curl command show above worked fine but I still got the "Log-on not successful." error. For me, the solution was to double quote my email address after the -a flag and to double quote my login (which was a full email address) after the -u flag. Shell was bash 5.2.37 on Debian 13.4.
