### ISSUE TITLE
gg and G

### ISSUE THREAD

**Issue by p-m-brown** [LukeSmithxyz/mutt-wizard#820] opened 2022-02-05 15:29 UTC
minor issue, i just note it: for the key bindings to work within the email (message body) i had to make the following change to mutt-wziard.muttrc:

```
bind pager,browser gg top-page
bind pager,browser G bottom-page 

```
changed this to:
```
bind pager gg top
bind pager G bottom
```

**Comment by zneix** [comment] 2022-06-21 12:47
Duplicate of #792

**Closed** 2022-06-21 16:59 UTC
