### ISSUE TITLE
Wired problem with lastest version of mutt-wizard-git

### ISSUE THREAD

**Issue by tramhao** [LukeSmithxyz/mutt-wizard#781] opened 2021-10-14 09:47 UTC
I just installed a new system thus mutt-wizard-git was installed. 
The problem is, I can read emails, but on the left side of the screen, which used to be the folders, disappear, also I have to comment first two lines in muttrc, or below errors will appear:
```
> neomutt 
Binding 'gM' will alias 'g'  Before, try: 'bind index g noop'  https://neomutt.org/guide/configuration.html#bind-warnings
Warning in /home/tramhao/.config/mutt/mw_gen_mutt_accounts.muttrc, line 4: 
Error in /home/tramhao/.config/mutt/muttrc, line 2: source: file /home/tramhao/.config/mutt/mw_gen_mutt_accounts.muttrc could not be sourced
Error in /home/tramhao/.config/mutt/muttrc, line 3: source: file /usr/share/mailwizard/mailwizard.muttrc could not be sourced
Binding 'g' will alias 'gM'  Before, try: 'bind index gM noop'  https://neomutt.org/guide/configuration.html#bind-warnings
source: errors in /home/tramhao/.config/mutt/muttrc
```

**Comment by PRESFIL** [comment] 2021-10-14 19:46
Looks like this issue is duplicate of #769.

Can you please accompany the removal of one and the backslash as described
in #771 and confirm there that it is the correct solution. I seem to have found a solution,
but the PR is still not merged.

**Closed** 2021-10-19 04:44 UTC
