### ISSUE TITLE
Error in mw -a 

### ISSUE THREAD

**Issue by gustavo-eduard** [LukeSmithxyz/mutt-wizard#650] opened 2021-02-11 03:26 UTC
dumb question.

Installed it from aur last week.

Got this error every time using mw -a example@test.com after retype password.
"
Log-on not successful.
 is not a valid account name.
"

Already give a try with different email´s with distinct domains.

**Comment by LukeSmithxyz** [comment] 2021-02-11 15:03
What is your domain?

**Comment by gustavo-eduard** [comment] 2021-02-11 16:35
@fh.com.br ; @tecnobrasao.com.br ; @gmail.com and hotmail as well.

In 2 first domains i insert correctly the imap and smtp port. It works in thunderbird

**Comment by spitfire-hash** [comment] 2021-02-11 17:13
same issue here with protonmail.

Source code says `<sth> is not a valid account name` will only be echoed when you call `delete` function, and give invalid account name. `  is not a valid account name` means we have gave  ` ` as account name(since we have none that's expected). But that should not be the case, since we just want to add an account not delete anything.

I don't want to debug the program myself, so if you need anything hmu.

**Comment by LukeSmithxyz** [comment] 2021-02-11 17:16
The delete function isn't the issue here (it runs to remove configs if login fails). I'll have that bogus error removed, bit it is not causing the issue.

Do you have `curl` installed? That's a new dependency that does log on. It's possible you got it before it was added as a requirement in the AUR build.

**Comment by spitfire-hash** [comment] 2021-02-11 17:20
Yeah, obviously, I do have `curl` installed.

**Comment by LukeSmithxyz** [comment] 2021-02-11 17:24
I haven't done testing with the new curl login with Protonmail, so it's possible it's buggy. It actually is probably trying to connect to the bridge encrypted. I'm probably going to have to bite the bullet and buy a Protonmail account just to be able to test this since so many people use their idiosyncratic system.

As for the OP, I'm going to guess that his problem is a lack of `curl`.

**Comment by spitfire-hash** [comment] 2021-02-11 17:31
I think that was my problem.

When I tried to configure the Protonmail Bridge, it didn't let me log in because I have to upgrade my account to a paid one in order to use the Bridge.

**Comment by gustavo-eduard** [comment] 2021-02-11 17:49
Have all dependencies installed, curl up and running here

![image](https://user-images.githubusercontent.com/32885732/107676821-54d43200-6c78-11eb-8fb0-70a70b8c7269.png)

**Comment by arawnx** [comment] 2021-02-16 20:46
I'm getting this issue too, fresh install of Arch.

**Comment by gustavo-eduard** [comment] 2021-02-16 20:52
What domains you using?

**Comment by arawnx** [comment] 2021-02-16 21:03
@gmail.com and a private domain hosted under Office 365

**Comment by davisi3** [comment] 2021-02-16 21:21
You have to create app password in gmail security settings and use that password in mw.

**Comment by FernandoBasso** [comment] 2021-02-21 10:58
> You have to create app password in gmail security settings and use that password in mw.

I have done that. It works with a simple manual configuration, but gives that error (from the opening post) with `mw -a ...`.

I have curl and other dependencies installed as well. I also tried providing the password with `-x 'mypassword'` and the result is the same: “Log-on not successful. is not a valid account name”.

**Comment by nishinsagume** [comment] 2021-02-21 15:22
> > You have to create app password in gmail security settings and use that password in mw.
> 
> I have done that. It works with a simple manual configuration, but gives that error (from the opening post) with `mw -a ...`.
> 
> I have curl and other dependencies installed as well. I also tried providing the password with `-x 'mypassword'` and the result is the same: “Log-on not successful. is not a valid account name”.

Enable the "Less secure app access" on your google settings, it would not work if you use 2FA.

**Comment by FernandoBasso** [comment] 2021-02-22 11:07
On Sun, Feb 21, 2021 at 07:22:23AM -0800, Nishimiya wrote:
> > > You have to create app password in gmail security settings and use that password in mw.
> > 
> > I have done that. It works with a simple manual configuration, but gives that error (from the opening post) with `mw -a ...`.
> > 
> > I have curl and other dependencies installed as well. I also tried providing the password with `-x 'mypassword'` and the result is the same: “Log-on not successful. is not a valid account name”.
> 
> Enable the "Less secure app access" on your google settings, it would not work if you use 2FA.
> 

Google does not offer me a way to enable “less secure apps” because I do
use 2-factor auth.

What other steps could I take to further debug this problem? Since it
works with my manual config using an app password, I am at a loss at the
moment on what else to try.

**Comment by LukeSmithxyz** [comment] 2021-02-22 13:10
Make an application password.

**Comment by FernandoBasso** [comment] 2021-02-22 16:38
On Mon, Feb 22, 2021 at 05:10:38AM -0800, Luke Smith wrote:
> Make an application password.

Perhaps my previous messages were written in a way that didn't make it
clear, but I _have_ done that. I have created an app password. I use it
with my manual config and it works there. In my previous messages I
spoke a little bit of the things I have tried so far (which is not much,
to be honest).

**Comment by LukeSmithxyz** [comment] 2021-02-22 17:23
Sorry. I'm responding my email so can't see the convo. I'll take a look
later when I can.

**Comment by SIX10** [comment] 2021-02-25 21:50
I'm using emailwiz on my server and get the same error on my local machine. I have a .pw domain, if that means anything.

**Comment by SIX10** [comment] 2021-02-25 21:54
> I'm using emailwiz on my server and get the same error on my local machine. I have a .pw domain, if that means anything.

I should add that muttwizard actually worked until I deleted my account. Trying to add back the same account gives the error.

**Comment by j4rr3d** [comment] 2021-02-26 08:16
Hi guys, same issue here, fresh installation arcoD (no bloat) + larbs, latest mw plus optional dependencies. When adding new account (just regular gmail), mw returns error **"Invalid range end 'xxxx.xxxx@gmail.com' is not valid email address"** ..... I had this setup working just a few days ago...but reinstalled the whole system :(. Let me know if I can help in any way.

**Comment by gustavo-eduard** [comment] 2021-02-26 09:40
Ok, i reverted commit to

**Comment by gustavo-eduard** [comment] 2021-02-26 09:42
ok, i reverted a few commits and it works for me 

Give a kick and returned to "Fix duplicate mailsync notifications" in Jan 24.
Going to make the test with more recent commits till find when it goes wrong

**Comment by LukeSmithxyz** [comment] 2021-02-26 12:20
I would assume that ddbf60ac093cab27d01497a5f0cfd44d4a3c0d5a could be a potential problem.

**Comment by gustavo-eduard** [comment] 2021-02-26 12:56
For moment, you can just pull some older version, add the email acc, and install the more recent back again.

**Comment by SIX10** [comment] 2021-02-26 18:48
Probably dumb question, but if I just pull an older version of mw, do I need to remove all the packages the newer version installed?

**Comment by Kr1ss-XD** [comment] 2021-02-26 19:48
FWIW This is probably related to #663 which Luke has fixed via https://github.com/LukeSmithxyz/mutt-wizard/commit/4d411d81798f652fcdfd55d866c4e78f8867a9bc - could you please try the latest -git trunk of `mw` ?

**Comment by Jonassenher** [comment] 2021-02-27 19:05
Same problem here. Using Outlook/Hotmail.

```
Log-on not successful.
 is not a valid account name.
```

**Comment by j4rr3d** [comment] 2021-02-27 19:18
@Kr1ss-XD I have been running the latest...would not post an issue if I would be using old version.

At the end I have tried the commit [ebb81bb](https://github.com/LukeSmithxyz/mutt-wizard/commit/ebb81bbcaa2f5ea694432396a4fcb0c000a1b88c) and everything worked fine. After the setup I have installed the latest version back again. Thanks for help!

**Comment by LukeSmithxyz** [comment] 2021-02-27 19:40
I'm really perplexed by this at this point because it seems like *everyone* is having issues, meanwhile I've been reinstalling everything over and over again from scratch and it always just werks. There must be something obvious I'm overlooking.

**Comment by annahri** [comment] 2021-02-28 13:15
Just installed the latest version via AUR, I got the same issue as well. (gmail)

**Comment by Jonassenher** [comment] 2021-02-28 14:37
> I'm really perplexed by this at this point because it seems like _everyone_ is having issues, meanwhile I've been reinstalling everything over and over again from scratch and it always just werks. There must be something obvious I'm overlooking.

Obvious question: When you tried from scratch again, did you also (temporarily) remove the configuration files related to mutt-wizard and its dependencies?

**Comment by gustavo-eduard** [comment] 2021-02-28 15:16
Ok, it now worked for me, i´m really stupid, and deserve hell. Was inserting port number 993 and 587 instead of imap and smtp address.

Can you guys send a print of whole process you are doing?

**Comment by genxer-io** [comment] 2021-02-28 15:30
Ive used this script a few times and it works perfectly --- albeit, i'm using my own domain and email - not google or the like.

**Comment by LukeSmithxyz** [comment] 2021-02-28 17:32
I have been testing it on a Google email I have as well and it does work perfectly fine. I have less secure applications enabled and no two-factor-authentication or any of that junk.

I'll spell out what I've been thinking of in case it isn't obvious. Now, the script tests logins with curl, and while this has always work on every domain I've tried, I suppose it's possible that some providers that do weird rerouting to other servers. This is why the `--location-trusted` (and implicit `-L` in there) is used, which solves every provier I've tested it on, but there might be more that need something else or can't be accessed via curl.

If anyone wants to try the curl command manually on their provider, it would be appreciated.

The other possibility is what @gustavo-eduard mentioned, i.e. a problem exists between the keyboard and chair, and it is possible that such an issue occurs many times such that it might seem to be a problem in the software when it is in reality not.

**Comment by LukeSmithxyz** [comment] 2021-02-28 17:37
I think I'm going to add some warning messages on failure that deal with common issues of people who don't read readmes, i.e. failure to enable less secure apps/IMAP on Gmail, failure to set up Protonmail Bridge, etc.

**Comment by SIX10** [comment] 2021-03-01 03:58
I am putting the correct ports, and my email server is on Vultr as well. Still get the error, and it only happened after I deleted my account from before. Is there a way to do a clean reinstall of muttwiz so I can see if it works then?

**Comment by Kr1ss-XD** [comment] 2021-03-01 16:01
@SIX10 From the top of my head - to remove the configuration, you could check the output of
```sh
find ~{,/.config} -maxdepth 1 -name '*mutt' -o -name '*mbsyncrc' -o -name '*msmtp*' -o -name '*notmuch*'
```
and _manually_ delete these files/folders. I'm suggesting to do that manually because the command _might_ find some false positives, which aren't related to `neomutt`, `mbsync`, `msmtp` or `notmuch`. Obviously, leave those in place.

How to uninstall the packages depends on the installation method you used. E.g. if you installed from AUR, `pacman -Rss` will take care of the dependencies as well.

**Comment by SIX10** [comment] 2021-03-01 17:55
@Kr1ss-XD Does pacman have the ability to uninstall packages from make install as well? I used -Rss mutt-wizard and uninstalled everything, then saw I built from source in downloads. Just wondering because I don't know if I accidently installed mw two times, which caused the issue. 

Anyways, reinstalled, built from source, confirm it works now. I'm not a shell expert, but was the problem possibly caused by the regex issue that was recently patched?

**Comment by Kr1ss-XD** [comment] 2021-03-01 18:03
>Does pacman have the ability to uninstall packages from make install as well?

No, you can do that with `make uninstall`.

>was the problem possibly caused by the regex issue that was recently patched?

If you had the same issue as @j4rr3d (`Invalid range end '...' is not valid email address`), then yes. Good to hear it's sorted out now, anyways !

**Comment by SIX10** [comment] 2021-03-04 15:26
> > Does pacman have the ability to uninstall packages from make install as well?
> 
> No, you can do that with `sudo make uninstall`.
> 
> > was the problem possibly caused by the regex issue that was recently patched?
> 
> If you had the same issue as @j4rr3d (`Invalid range end '...' is not valid email address`), then yes. Good to hear it's sorted out now, anyways !

Never had the invalid range part, just the "is not a valid account name"

**Comment by thiccpad** [comment] 2021-03-17 09:29
this happens for me with a yandex.com address. Although it's saying `Log-on not successful.`

**Comment by andrewpap22** [comment] 2021-03-24 21:31
Having a `Log-on not successful` here as well. 
 - I have LARBS installed (so I guess `mw` was already installed with all the dependencies needed)
 - Got the gpg key done and the pass init as well. 
And then the command which I used to setup my email is: 

```bash
$ mw -a qwerty@cern.ch -i imap.cern.ch -I 993 -s smtp.cern.ch -S 587 -x "qwerty" -n "qwerty qwerty"
```

**Comment by Kr1ss-XD** [comment] 2021-03-24 21:45
Not sure if that's the problem here, but as I was just reading the output of `mw -h`, I noticed that it recommends to enclose the password in double quotes. 

This might be an issue though, in case that password contains characters like one or more of :
```
$ \ ` "
```
since the shell would interpret those.

Just a shot in the dark, but if that is the case, please try to enclose the password in single quotes.

**Comment by andrewpap22** [comment] 2021-03-24 21:49
Hi Kr1ss, thank you for your answer. 
I already knew that, so I had already tried to get the password in single quotes but still getting the same `Log-on not successful`

**Comment by LukeSmithxyz** [comment] 2021-03-24 21:52
Single quotes wouldn't make it better. You might have to escape special characters interpreted by your shell. LARBS uses zsh and it will interpret, for example `!` as something special and a bunch of other characters as well, so they should be escaped.

Try *not* giving your password via `-x` on the command line and `mw` will prompt you for it. You will not have to quote or escape anything in that case.

See if that works and that will show you if it's a password-via-cli problem or a server problem (I expect the former).

**Comment by LukeSmithxyz** [comment] 2021-03-24 21:53
I'm going to close this issue though because it's really different people having different problems.

**Closed by LukeSmithxyz** 2021-03-24 21:53 UTC

**Comment by andrewpap22** [comment] 2021-03-24 21:55
> Single quotes wouldn't make it better. You might have to escape special characters interpreted by your shell. LARBS uses zsh and it will interpret, for example `!` as something special and a bunch of other characters as well, so they should be escaped.
> 
> Try _not_ giving your password via `-x` on the command line and `mw` will prompt you for it. You will not have to quote or escape anything in that case.
> 
> See if that works and that will show you if it's a password-via-cli problem or a server problem (I expect the former).

Thank you for your answer as well Luke. Already tried that as well. Still getting the same message.

**Comment by LukeSmithxyz** [comment] 2021-03-24 22:01
Try giving `-u qwerty` as well. I'm looking at the Cern website, and it's ambiguous whether people login as usernames or email addresses.

**Comment by andrewpap22** [comment] 2021-03-24 22:04
You was right, I don't know how I didn't think about it. Everything at CERN works by logging in with your username, but I wouldn't think that is the case as well for the email. But yeah that was it. Thank you very much, I appreciate your help and time! Best wishes !
