### ISSUE TITLE
Errors when launching mutt after wizard

### ISSUE THREAD

**Issue by insanerwayner** [LukeSmithxyz/mutt-wizard#17] opened 2018-02-21 03:10 UTC
When launching mutt I'm getting these errors. 
```
Error in /home/wayne/.config/mutt/accounts/Outlook.muttrc, line 29: +sent-mail: unknown command
Error in /home/wayne/.config/mutt/accounts/Outlook.muttrc, line 30: +Sent: unknown command
Error in /home/wayne/.config/mutt/accounts/Outlook.muttrc, line 32: +Drafts: unknown command
Error in /home/wayne/.config/mutt/personal.muttrc, line 2: source: errors in /home/wayne/.config/mutt/accounts/Outlook.muttrc
Error in /home/wayne/.config/mutt/muttrc, line 7: source: errors in /home/wayne/.config/mutt/personal.muttrc
Error: impossible to build path of 'etc/aliases'.
Error in /home/wayne/.config/mutt/muttrc, line 8: 
source: errors in /home/wayne/.config/mutt/muttrc
Error: issue converting path to absolute (No such file or directory)Press any key to continue...
```

Then once I go ahead and continue it shows all my folders like it should but when I do the keybindings to get to them it is not behaving, saying something either ```key not bound``` or ```there are no messages```

**Comment by LukeSmithxyz** [comment] 2018-02-21 03:42
Show me your muttrc and accounts/Outlook.muttrc.

Could you also show me the output of `ls ~/.mail/Outlook/`?

**Comment by insanerwayner** [comment] 2018-02-21 14:59
## muttrc
```
# vim: filetype=neomuttrc
# This is the general mutt config which has the settings that all accounts use.
bind index,pager i noop
bind index,pager g noop
bind index \Cf noop
source etc/muttcol
source personal.muttrc
source etc/aliases
set sleep_time = 0
set sort = 'reverse-date'
set editor = vim
#set copy = no
set timeout = "5"
set mail_check = "10"
set mailcap_path = ~/.config/mutt/etc/mailcap
set date_format="%m/%d %I:%M"
set index_format="%2C %Z %D %-15.15F %s (%-4.4c)"
set markers = no
set mark_old = no
auto_view text/html
auto_view application/pdf
alternative_order text/plain text/enriched text/html

# General remappings
bind editor <space> noop
bind index G last-entry
bind index gg first-entry
bind index d half-down
bind index u half-up
bind index D delete-message
bind index U undelete-message
bind index F search
bind index,pager R group-reply
macro index,pager S '<sync-mailbox>
macro index,pager \Cu |urlview\n

# Notmuch searching
macro index \Cf "<enter-command>unset wait_key<enter><shell-escape>read -p 'notmuch query: ' x; echo \$x >~/.cache/mutt_terms<enter><limit>~i \"\`notmuch search --output=messages \$(cat ~/.cache/mutt_terms) | head -n 600 | perl -le '@a=<>;chomp@a;s/\^id:// for@a;$,=\"|\";print@a'\`\"<enter>" "show only messages matching a notmuch pattern"
macro index A "<limit>all\n" "show all messages (undo limit)"

# Sidebar mappings
set sidebar_visible = yes
set sidebar_width = 20
set sidebar_short_path = yes
set sidebar_next_new_wrap = yes
set mail_check_stats
set sidebar_format = '%B%?F? [%F]?%* %?N?%N/?%S'
bind index,pager \Ck sidebar-prev
bind index,pager \Cj sidebar-next
bind index,pager \Co sidebar-open
bind index,pager <F3> sidebar-page-up
bind index,pager <F4> sidebar-page-down
bind index,pager \Cp sidebar-prev-new
bind index,pager \Cn sidebar-next-new
bind index,pager B sidebar-toggle-visible
```
## accounts/Outlook.muttrc
```
# vim: filetype=neomuttrc
# muttrc file for account Outlook
set realname = "Wayne Reeves"
set from = "darthwayne@hotmail.com"
set smtp_url = "smtp://darthwayne@hotmail.com@smtp-mail.outlook.com:587/"
set sendmail = "/usr/bin/msmtp -a Outlook"
set folder = "~/.mail/Outlook"
set header_cache = ~/.config/mutt/accounts/Outlook/cache/headers
set message_cachedir = ~/.config/mutt/accounts/Outlook/cache/bodies
set certificate_file = ~/.config/mutt/accounts/Outlook/certificates
source "~/.config/mutt/credentials/getmuttpass Outlook |"

set mbox_type = Maildir
set ssl_starttls = yes
set ssl_force_tls = yes

bind index,pager g noop
bind index gg first-entry
mailboxes =Junk =[hotmail].Sent Mail =[hotmail].Drafts =Drafts =Deleted.Snoozed =Deleted =Notes =POP =sent-mail =POP.wayne.reeves@outlook.com =Inbox =Unroll.me =darthwayne@outlook.com =Outbox =[hotmail] =Archive =Sent =Unroll =darthwayne@outlook =POP.wayne =POP.wayne.reeves@outlook
macro index,pager gi "<change-folder>=darthwayne@outlook<enter>" "Go to inbox."
macro index,pager gs "<change-folder>=[hotmail].Sent Mail<enter>" "Go to sent."
macro index,pager gs "<change-folder>=sent-mail<enter>" "Go to sent."
macro index,pager gs "<change-folder>=Sent<enter>" "Go to sent."
macro index,pager gd "<change-folder>=[hotmail].Drafts<enter>" "Go to drafts."
macro index,pager gd "<change-folder>=Drafts<enter>" "Go to drafts."
macro index,pager ga "<change-folder>=Archive<enter>" "Go to archive."
set spoolfile = "+darthwayne@outlook"
set record = "+[hotmail].Sent Mail
+sent-mail
+Sent"
set postponed = "+[hotmail].Drafts
+Drafts"
```

## ls ~/.mail/Outlook/
```
Archive             darthwayne@outlook.com  Deleted.Snoozed  [hotmail]         [hotmail].Sent Mail  Junk   Outbox  POP.wayne                 POP.wayne.reeves@outlook.com  sent-mail  Unroll.me
darthwayne@outlook  Deleted                 Drafts           [hotmail].Drafts  Inbox                Notes  POP     POP.wayne.reeves@outlook  Sent                          Unroll
```

**Comment by LukeSmithxyz** [comment] 2018-02-21 15:13
Did you give multiple email addresses the same name: "Outlook"? If so, that's your problem.

Otherwise it looks like Outlook has an extremely redundant directory structure that it isn't reading correctly. I've pushed a change to the repo that should ensure it only auto-detects one mailbox for each category (sent/drafts). Retry the script and see what happens.

**Comment by insanerwayner** [comment] 2018-02-21 15:17
Just one account, I have multiple aliases within my account which each have theirj own folders. Cleaning up now and trying again.

**Comment by LukeSmithxyz** [comment] 2018-02-21 15:26
Ah I see. Well I think that's going to be a problem then with the shortcuts, because what the script does now is search for a box with the sequence "(S/s)ent" and assumes it's the sent box (same for drafts and everything else), so probably what you'll get is that one of your different boxes (whichever grep returns first) will be assigned as the place where your mail goes and that gets the shortcut.

At least that's with the update I just pushed. Beforehand it was just returning **all** related boxes and thus creating a bad muttrc.

You also might have to manually set your "from" address if you want to send from multiple accounts.

**Comment by insanerwayner** [comment] 2018-02-21 15:37
That makes sense. It is working better this time( I can get into a couple of the folders). I will probably just need to go in and set my own bindings for the folders I need to get into. Honestly, some of those folders may just be things that were created from other mail clients over the last 20 years I've had this account. 

However, I did notice that the script didn't play nicely with the a *"."* in the email address. It changed my **"wayne.reeves@outlook.com"** to **'reeves@outlook.com"** in the sidebar in mutt.

**Comment by LukeSmithxyz** [comment] 2018-02-21 16:00
Oh yeah, the reeves@outlook thing is because the sidebar by default tries to smartly trim your box names. To undo that, just change the `sidebar_short_path` variable in the muttrc.

**Comment by insanerwayner** [comment] 2018-02-21 16:38
still getting these errors when launching:
```
Error in /home/wayne/.config/mutt/etc/muttcol, line 14: 8: color not supported by term
Error in /home/wayne/.config/mutt/etc/muttcol, line 15: 8: color not supported by term
Error in /home/wayne/.config/mutt/muttrc, line 6: source: errors in /home/wayne/.config/mutt/etc/muttcol
source: errors in /home/wayne/.config/mutt/muttrc
```

**Comment by LukeSmithxyz** [comment] 2018-02-21 16:43
What terminal are you using?

**Comment by insanerwayner** [comment] 2018-02-21 17:04
Currently I'm SSHed in from a work Windows PC. On the actual machine I use guake and gnome-terminal and I was getting those there as well.

**Comment by Duke9289** [comment] 2018-07-16 02:37
Hey, sorry to resurrect an old issue, I was having a similar problem with muttwizard on my machine, getting those last errors that were mentioned, found this thread, and figured I'd share my fix if anyone else sees this.  In ~/config/mutt/etc/muttcol,  I had one line that initially read

``
color sidebar_divider color8 black
``

This is the only place where the color was named as `color8`, everywhere else it has a name like black or brightyellow or whatever.  I changed that line to use the same color naming convention as every other line, so it read 

``
color sidebar_divider brightblack black
``

and the problem went away.  This is on a Debian testing (buster) machine, using urxvt as my terminal.  Weirdly, on my Arch laptop also running urxvt, it's completely fine with the color8 naming method.  I'm not yet sure why one is okay with it and another isn't.

**Comment by LukeSmithxyz** [comment] 2018-07-16 14:11
Oh thanks---actually, I feel silly for not noticing that before! That actually makes perfect sense as the cause of the error.

I'm not sure if @insanerwayner is still using this, but I'd assume that it'd solve his problem.

I've pushed the change to the repo and unless someone is still getting the problem, I think I'll close this issue soon.

**Closed** 2018-07-17 21:39 UTC
