### ISSUE TITLE
Error: flattened mailbox name ... contains canonical hierarchy delimiter

### ISSUE THREAD

**Issue by benhourigan** [LukeSmithxyz/mutt-wizard#546] opened 2020-10-14 06:17 UTC
After using `mw -a [any Google address]`, `mw -y [address]` returns an error, eg,

````
C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
Error: flattened mailbox name 'XXXX.XXXX/XXXX' contains canonical hierarchy delimiter
C: 1/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
No new mail.
````
Running on macOS 10.15.7, `neomutt` version stable 20200925, installed with `brew`, including dependencies. 

Previously had a working `mutt` install with a Gmail account set up and no errors.

**Comment by f380cedric** [comment] 2020-10-14 07:42
Seems to be a duplicate of #517, See the second part of https://github.com/LukeSmithxyz/mutt-wizard/issues/517#issuecomment-684506780.

**Comment by PRESFIL** [comment] 2020-12-30 11:18
I also thought it was a duplicate before, but these are two different issues.

This issue about conversion of delimiter **after server** (Error: **flattened mailbox name** 'XXXX.XXXX/XXXX' contains canonical hierarchy delimiter);

issue #517 -  about canonical delimiter **on server** (Error: **canonical mailbox name** 'Archive.2018' contains flattened hierarchy delimiter).

**Comment by PRESFIL** [comment] 2020-12-30 11:26
Some "prudent" services (mail.ru, protonmail.com) use `/` as a hierarchy delimiter, which causes error of this topic (**first, 1**).

However, when you try to replace it with something else using `Flatten`, the second one issued (**second error, 2**).

Nothing can be done with the **1** one. But the **2** one can be avoided, which is what I suggested in the #600 .

**Comment by PRESFIL** [comment] 2020-12-30 11:32
Also, these error messages that @benhourigan sent, I also have and break the `getboxes` function, which spoils the mutt config and there are no mailboxes, only this:

```mutt
mailboxes "=INBOX" "=All Mail" "=Archive" "=Authentication" "=Drafts" "=Sent" "=Spam" "=Starred" "=Trash" "=C: 0.1  B: 0/9  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0"
```

I tried use `-q/--quiet` `mbsync` flag, but it ignored.

I can of course use `mw -f`, but this is only as a last resort and will have to manually *somehow* add my mailboxes.

**Comment by josh-spatial** [comment] 2021-01-12 06:04
When I setup my gmail account I had to comment out the 
```#Flatten .``` in ```.mbsyncrc```, then it worked.  But, I'm not sure if my folders are really correct.  But it's working well enough until I can find a replacement for gmail.  Trying protonmail, but now that isn't setting up with mutt-wizard (log-on) :)

**Comment by PRESFIL** [comment] 2021-01-12 21:05
Previously, I thought that `mutt` can't work with nested mailboxes, apparently because of the mention in `mbsync(1)`:

>        Flatten delim
>              Flatten the hierarchy within this Store by substituting the canonical hierarchy delimiter / with delim.  This can be useful when the MUA used to access the Store provides suboptimal handling of
>              hierarchical mailboxes, as is the case with Mutt.  A common choice for the delimiter is ..
>              Note that flattened sub-folders of the INBOX always end up under Path, including the "INBOXdelim" prefix.

So you commented out `Flatten .` before the first sync and after the sync you have tree mailboxes?  
Are they displayed normally in the sidebar?  

I also wonder if `notmuch` can work with such mailboxes (I don't use notmuch). Maybe they should be flat for him.

**Comment by josh-spatial** [comment] 2021-01-12 23:22
That is the thing, I don't know what normal looks like.  I could send you some screenshots of my hierarchy:

`xxxx@gmail.com/[Gmail]` and the [Gmail] folder has ```/'All Mail'   Drafts      new          Spam      tmp
 cur         Important  'Sent Mail'   Starred   Trash ``` subfolders.
 
Then I have this one on the same level as Gmail:
`xxxx@gmail.com/INBOX` and this folder has ```cur  new  tmp```

Does this look right???

**Comment by PRESFIL** [comment] 2021-01-13 18:41
If I understand correctly, then your account in the file system now looks like this:

1) *Hierarchical*:

```sh
xxxx@gmail.com/
├── [Gmail]
│   ├── All Mail
│   ├── cur
│   ├── Drafts
│   ├── Important
│   ├── new
│   ├── Sent Mail
│   ├── Spam
│   ├── Starred
│   ├── tmp
│   └── Trash
└── INBOX

12 directories, 0 files
```

And not like this:

2) *Flattened*:

```
xxxx@gmail.com/
├── [Gmail]
├── [Gmail].All Mail
├── [Gmail].cur
├── [Gmail].Drafts
├── [Gmail].Important
├── [Gmail].new
├── [Gmail].Sent Mail
├── [Gmail].Spam
├── [Gmail].Starred
├── [Gmail].tmp
├── [Gmail].Trash
└── INBOX

12 directories, 0 files
```

That's what I was asking. In the first case, everything works correctly for you and you can normally switch between folders in `mutt`? I also wonder if `notmutch` will work normally in this case.

> ...and this folder has cur new tmp

This is the internal content of each mailbox that `mbsync` created to work with. I'm interested specifically about the *user's hierarchy*.

**Comment by josh-spatial** [comment] 2021-01-13 23:36
Yes, my directory looks like #1, but I've got the ```/cur /new /temp``` folders also under INBOX.  

So, after I've been playing with it, I think that my hierarchy was a bit jacked up with the commented out ```Flatten .``` line.  Because I noticed today that when I delete messages from ```INBOX``` that gmail also marked as "important", **a duplicate message also remains** in my ```[Gmail]/Important``` folder.  So something isn't quite right.

I'm uninstalling and going to try again from scratch.  I'm think about switching to protonmail, if they just had a calendar :)  

I might try to set mine up again without mbsync, since I'm mostly always online and don't have shotty internet like some others, ahem...

**Comment by josh-spatial** [comment] 2021-01-14 03:21
I reinstalled mw from scratch.  I didn't change anything, and here is what I get when I try to sync:
`   ~  mw -Y
C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
Error: flattened mailbox name '[Gmail]/Sent Mail' contains canonical hierarchy delimiter
Error: flattened mailbox name '[Gmail]/Starred' contains canonical hierarchy delimiter
Error: flattened mailbox name '[Gmail]/Spam' contains canonical hierarchy delimiter
Error: flattened mailbox name '[Gmail]/Drafts' contains canonical hierarchy delimiter
Error: flattened mailbox name '[Gmail]/Important' contains canonical hierarchy delimiter
Error: flattened mailbox name '[Gmail]/Trash' contains canonical hierarchy delimiter
Error: flattened mailbox name '[Gmail]/All Mail' contains canonical hierarchy delimiter
C: 1/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
Found 0 total files (that's not much mail).
No new mail.
`

**Comment by josh-spatial** [comment] 2021-01-14 04:12
So, used the ```-o``` option and it works fine online only....

**Comment by PRESFIL** [comment] 2021-01-16 11:51
I thought you'd comment out `Flatten .`.

I tried it myself:
1. I created an account with the `-f` option to not start syncing
2. commented out `Flatten .`
3. started syncing with `mw <account>`
 
Everything works (except that you have to edit the mailboxes manually).

**Comment by josh-spatial** [comment] 2021-01-16 13:54
I used the `-o` option after reinstall to keep `mbsync` out of the equation, since that seems to be my problem.  

Does deleting mail from your `INBOX` also delete that mail from the `Important` mailbox after commenting out the `Flatten .` ?

**Comment by PRESFIL** [comment] 2021-01-17 06:56
Deleting `Flatten .` disables path conversion (see [1](https://github.com/LukeSmithxyz/mutt-wizard/issues/546#issuecomment-752423567) [2](https://github.com/LukeSmithxyz/mutt-wizard/issues/546#issuecomment-752431994) [3](https://github.com/LukeSmithxyz/mutt-wizard/issues/546#issuecomment-752441501)). Now, `mbsync` using, but mailbox is now *hierarchical*. This is about the main topic.

> Does deleting mail from your `INBOX` also delete that mail from the `Important`...

I think this is some kind of gmail specific/server-side automation, it is not related in any way. It is possible for you/gmail online '-o' mailbox - the best solution. Perhaps you can make some kind of hook in your `mutt`'s account settings.

**Comment by karlb** [comment] 2021-01-17 08:35
I also have the same problem. Commenting out `Flatten .` allows the sync to work in my case, too.

However, the sidebar in neomutt does not show any names for my mailboxes. I don't know if that is related.

**Comment by PRESFIL** [comment] 2021-01-17 09:18
It seems to me that this is due to the fact that now the mailbox in the file system **has a different structure**. You need to update your mailboxes (`mailboxes` statement inside particular account file, [1](https://github.com/LukeSmithxyz/mutt-wizard/issues/546#issuecomment-761550914)). Or use [this trick](https://github.com/LukeSmithxyz/mutt-wizard/issues/620#issuecomment-761551939).

**Comment by karlb** [comment] 2021-01-17 13:53
The missing sidebar labels were caused by a too old neomutt version. Using a more recent one shows the mailbox names as intended. The mailboxes have been found correctly by both the old and new version (using `c` to switch mailboxes also showed their names).

**Comment by bryall** [comment] 2021-01-28 04:51
getting the same error with a gmail account  , what is the optimal way to resolve this?

**Closed** 2021-01-30 21:42 UTC
